language: python
before_install:
- pip install pycodestyle
install:
- pip install -r requirements.txt
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
- pytest --cov=artellapipe
- sphinx-apidoc -f -e -o docs/sphinx artellapipe
- sphinx-build -M html ./docs/sphinx ./
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: kWbLBT+TtxNbRWP6sIkFYfsQS46yCLM88Xke8xtJBOqlgUVl/ao5G++KH7u9kTC8pfpHi/r5Ac2uqrk3hgvRFW5xY18zq3oMrGr1g7xWtg3Mb7MoMsuyfb4xXRHHxYliHfuRIYKaBUE7FMmDl2ZG1BlFgn70nIS5+B5uI7XO34SdgtB2gwfXQOMFgLzY7NUe4k/kiuj6fTqu7EFLiKAdGdYLKbK6VShO/KCgF+EGoBsVl04xEsv6Gi59AL8q7A3r4AixQBBLjilAi8tpFL9r/RZSFc21SM7PiUHd1MPtqJbgLqj4SjBiuL1NRdJqM/D9gnxcEys7ydfTZC4tmxGL/DWdMu4tmAcskm93a5oOVd/Y0oK2IoULH711osnEYAgfHZhl7mS+MskPK8olT9VBI3q7/Khw8nr0IKYQH7eHjjqFxxk2SHyl4kwlOfup5fY7e9x9m9Dcs99tv7G0EF9KqR1fxf11pTKUxhjDb8Cm2KrOfNMfThwQRxc6RXHfJVAu/LjNvBYnqbrsdRMTi/zlZTIQqmXN3ObPcBWEJlA0DdZm6qTMLS50fOmq27frwJuaBjHfw9myHQkAcfiGEDPosNPT+MYzhq/7i53BvO3bPHHAtZsxHTuutdH/zoGTyV7m3g3ntJbCb8PLAbbIaf/rlP9DSdHSYq0M9n8LCPzD7wQ=
    on:
      branch: master
      tags: true